### ISSUE TITLE
`lein with-profile :openjfx11 repl` fails with a weird error message

### ISSUE THREAD

**Issue by behrica** [joinr/vegafx#3]
```
lein with-profile :openjfx11 repl
```
-> 

```
Performing task 'repl' with profile(s): ''
Warning: profile : not found.
Warning: profile : not found.
Warning: no nREPL dependency detected.
Be sure to include nrepl/nrepl in :dependencies of your profile.
Error loading nrepl.server: Could not locate nrepl/server__init.class, nrepl/server.clj or nrepl/server.cljc on classpath.
Error loading complete.core: Could not locate complete/core__init.class, complete/core.clj or complete/core.cljc on classpath.
Syntax error (ClassNotFoundException) compiling at (/tmp/form-init1180296858344210818.clj:1:1795).
nrepl.server
```

**Comment by joinr** [comment]
I was getting the same problem (I never tested this specifically, since I was running on java 1.8).

I replicated the problem.  Looks like the example invocation is wrong for leiningen, specifically:

lein with-profile openjfx11 repl

will bring the dependencies in as expected, but you still get the error message with the nrepl stuff.
If you just invoke the profile additively, with +, I get no errors:

lein with-profile +openjfx11 repl

Updated readme to show new invocation in d4632abd530d216fe47e85caaae5d9969aafe734
